"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['brush copy.py']
DATA_FILES = ['brush.py',
 'canvas.py',
 'geometry.py',
 'gui.py',
 'marchingsquares.py',
 'orderedset.py',
 'painter.py',
 'setup.py',
 'stroke.py',
 'test.py',
 'circleIcon.jpg',
 'squareIcon.jpg',
 'triangleIcon.jpg']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
